branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.14.2\mingw73_32
  - choco install -y InnoSetup
  - set PATH=%PATH%;%QTDIR%\bin;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - qmake TestProject.pro
  - mingw32-make
after_build:
  - windeployqt release/TestProject.exe
  - cmd: cp LICENSE release/LICENSE.txt"
  - iscc innosetup.iss
  - rm release/*.o
  - rm release/*.cpp

artifacts:
  - path: Output\YOUR-APP-*.exe
  - path: release
    type: zip