install:
  - set QTDIR=C:\Qt\5.9.9\mingw53_32
  - choco install -y InnoSetup
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;"C:\Program Files (x86)\Inno Setup 6";
build_script:
  - qmake TestProject.pro
  - mingw32-make

after_build:
  - windeployqt release/TestProject.exe
  - iscc innosetup.iss
  - rm release/*.o
  - rm release/*.cpp

artifacts:
  - path: Output\YOUR-APP-*.exe
  - path: release
    type: zip