branches:
  only:
    - master
    
environment:
    matrix:
    - name: win32
      platform: amx64_x86
      qt: msvc2017

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - set QTDIR=C:\Qt\5.9.9\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin;
  - qmake
  - nmake & exit 0